### PR TITLE
feat(use-mutative): upgrade mutative version to `0.4.2`

### PR DESCRIPTION
**Pull request by ZouYouShun**

### CODE REVIEW

**Comment by unadlib** [comment]
`replaceResult = { . .result };` It looks like state must be a plain object.

**Comment by unadlib** [comment]
`const nextState = create(reducer)(state) ` may be clearer.

**Comment by ZouYouShun** [comment]
> `replaceResult = { . .result };` It looks like state must be a plain object.

oh! that just example

**Comment by ZouYouShun** [comment]
> `const nextState = create(reducer)(state) ` may be clearer.

sorry for not found that comment,
not sure what is that mean, still not released, we can update later.

**Pull request merged**
